import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics book with collapsible chapters
  bookSidebar: [
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI & Humanoid Robotics',
      collapsible: true,
      collapsed: true,
      items: [
        'chapters/chapter-1/index',
        'chapters/chapter-1/introduction',
        'chapters/chapter-1/learning-objectives',
        'chapters/chapter-1/what-is-physical-ai',
        'chapters/chapter-1/understanding-humanoid-robotics',
        'chapters/chapter-1/applications',
        'chapters/chapter-1/relationship-ai-physical-systems',
        'chapters/chapter-1/technical-foundations',
        'chapters/chapter-1/chapter-summary',
        'chapters/chapter-1/lab-exercise',
        'chapters/chapter-1/further-reading'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: ROS 2 for Physical AI Applications',
      collapsible: true,
      collapsed: true,
      items: [
        'chapters/chapter-2/index',
        'chapters/chapter-2/learning-objectives',
        'chapters/chapter-2/introduction-ros2',
        'chapters/chapter-2/ros2-architecture',
        'chapters/chapter-2/ros2-physical-ai',
        'chapters/chapter-2/designing-ros2-packages',
        'chapters/chapter-2/best-practices',
        'chapters/chapter-2/chapter-summary',
        'chapters/chapter-2/lab-exercise',
        'chapters/chapter-2/further-reading'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Simulation Environments for Physical AI',
      collapsible: true,
      collapsed: true,
      items: [
        'chapters/chapter-3/index',
        'chapters/chapter-3/learning-objectives',
        'chapters/chapter-3/role-of-simulation',
        'chapters/chapter-3/gazebo',
        'chapters/chapter-3/unity-robotics',
        'chapters/chapter-3/ros2-integration',
        'chapters/chapter-3/best-practices',
        'chapters/chapter-3/chapter-summary',
        'chapters/chapter-3/lab-exercise',
        'chapters/chapter-3/further-reading'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: NVIDIA Isaac and Vision-Language-Action Systems',
      collapsible: true,
      collapsed: true,
      items: [
        'chapters/chapter-4/index',
        'chapters/chapter-4/learning-objectives',
        'chapters/chapter-4/introduction-nvidia-isaac',
        'chapters/chapter-4/nvidia-isaac-sim',
        'chapters/chapter-4/vla-systems',
        'chapters/chapter-4/nvidia-isaac-ros',
        'chapters/chapter-4/implementing-vla',
        'chapters/chapter-4/evaluation',
        'chapters/chapter-4/chapter-summary',
        'chapters/chapter-4/lab-exercise',
        'chapters/chapter-4/further-reading'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5: Advanced Physical AI Concepts',
      collapsible: true,
      collapsed: true,
      items: [
        'chapters/chapter-5/index',
        'chapters/chapter-5/learning-objectives',
        'chapters/chapter-5/advanced-concepts',
        'chapters/chapter-5/advanced-control',
        'chapters/chapter-5/sensor-fusion',
        'chapters/chapter-5/ethical-considerations',
        'chapters/chapter-5/future-directions',
        'chapters/chapter-5/research-challenges',
        'chapters/chapter-5/designing-systems',
        'chapters/chapter-5/chapter-summary',
        'chapters/chapter-5/lab-exercise',
        'chapters/chapter-5/further-reading'
      ],
    },
  ],
};

export default sidebars;
